version: '3.6' 

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /ck_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ck_project
    ports:
      - 8000:8000
    depends_on: 
        - db


volumes:
  postgres_data:

